apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-metrics
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: {{ .Values.container.containerPort | default 9090 }}
      targetPort: {{ .Values.container.containerPort | default 9090 }}
      protocol: TCP
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
