apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.readinessProbe.httpGet.path | default "/readyz" }}
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: {{ .Values.readinessProbe.periodSeconds | default 10 | squote }}
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: {{ .Values.readinessProbe.timeoutSeconds | default 5 | squote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.containerPort | default 8080 }}
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-preview
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.containerPort | default 8080 }}
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-mcp
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.readinessProbe.httpGet.path | default "/readyz" }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.mcpPort | default 8081 }}
      targetPort: {{ .Values.container.mcpContainerPort | default 8081 }}
      protocol: TCP
      name: mcp
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
