apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  metrics:
    - name: success-rate
      interval: 30s
      count: 5
      successCondition: result[0] >= 0.95
      failureLimit: 2
      provider:
        prometheus:
          address: http://prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(http_requests_total{
              service="{{ include "app.fullname" . }}",
              code=~"2..|3.."
            }[1m]))
            /
            sum(rate(http_requests_total{
              service="{{ include "app.fullname" . }}"
            }[1m]))
    - name: p95-latency-ms
      interval: 30s
      count: 5
      successCondition: result[0] <= 800
      failureLimit: 2
      provider:
        prometheus:
          address: http://prometheus.monitoring.svc.cluster.local:9090
          query: |
            histogram_quantile(0.95,
              sum(rate(http_request_duration_seconds_bucket{
                service="{{ include "app.fullname" . }}"
              }[1m])) by (le)
            ) * 1000
