apiVersion: v1
kind: ConfigMap
metadata:
  name: team-vault-hostname-map
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  hostname-map.yaml: |
    mappings:
      {{- range $hostname, $user := .Values.hostnameMap.mappings }}
      {{ $hostname }}: {{ $user }}
      {{- end }}
    trustOsUserFallback: {{ .Values.hostnameMap.trustOsUserFallback }}
    knownOsUsers:
      {{- range .Values.hostnameMap.knownOsUsers }}
      - {{ . }}
      {{- end }}
    unknownPrefix: {{ .Values.hostnameMap.unknownPrefix | quote }}
