apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  timeZone: {{ .Values.cron.timeZone | default "Etc/UTC" | quote }}
  concurrencyPolicy: {{ .Values.cron.concurrencyPolicy | default "Forbid" }}
  successfulJobsHistoryLimit: {{ .Values.cron.successfulJobsHistoryLimit | default 3 }}
  failedJobsHistoryLimit: {{ .Values.cron.failedJobsHistoryLimit | default 3 }}
  startingDeadlineSeconds: {{ .Values.cron.startingDeadlineSeconds | default 300 }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cron.backoffLimit | default 1 }}
      activeDeadlineSeconds: {{ .Values.cron.activeDeadlineSeconds | default 86400 }}
      template:
        metadata:
          labels:
            {{- include "app.selectorLabels" . | nindent 12 }}
            {{- include "app.commonLabels" . | nindent 12 }}
        spec:
          restartPolicy: {{ .Values.cron.restartPolicy | default "OnFailure" }}
          serviceAccountName: {{ include "app.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 600 }}
          containers:
            - name: {{ include "app.fullname" . }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- if hasKey .Values "envVariablesFromSecrets" }}
              envFrom:
                - secretRef:
                    name: {{ include "app.fullname" . }}-secret
              {{- end }}
              {{- with .Values.container.env }}
              env:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              {{- with .Values.container.volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- with .Values.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
