{{- $prefix := include "app.fullname" . }}
{{- $labels := include "app.labels" . }}
{{- with .Values.envVariablesFromSecrets }}
{{- if $.Capabilities.APIVersions.Has "external-secrets.io/v1" }}
apiVersion: external-secrets.io/v1
{{- else }}
apiVersion: external-secrets.io/v1beta1
{{- end }}
kind: ExternalSecret
metadata:
  name: {{ $prefix }}-external-secret
  namespace: {{ $.Values.app.namespace }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $prefix }}-cluster-secret-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    name: {{ $prefix }}-secret
  data:
    {{- toYaml . | nindent 4 }}
---
{{- if $.Capabilities.APIVersions.Has "external-secrets.io/v1" }}
apiVersion: external-secrets.io/v1
{{- else }}
apiVersion: external-secrets.io/v1beta1
{{- end }}
kind: ClusterSecretStore
metadata:
  name: {{ $prefix }}-cluster-secret-store
  namespace: external-secrets
  labels:
    {{- $labels | nindent 4 }}
spec:
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: sa-external-secrets
            namespace: kube-system
{{- end }}
