{{- if .Values.keda.enabled }}
{{- $queueURL := "" -}}
{{- range .Values.container.env -}}
  {{- if eq .name "SQS_WORK_QUEUE_URL" -}}
    {{- $queueURL = .value -}}
  {{- end -}}
{{- end -}}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "app.fullname" . }}-auth
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  podIdentity:
    provider: aws
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "app.fullname" . }}
  pollingInterval: {{ .Values.keda.pollingInterval | default 30 }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod | default 300 }}
  minReplicaCount: {{ .Values.keda.minReplicaCount | default 0 }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount | default 20 }}
  triggers:
    {{- range .Values.keda.triggers }}
    - type: {{ .type }}
      metadata:
        queueURL: {{ $queueURL | quote }}
        queueLength: {{ .queueLength | quote }}
        awsRegion: {{ .awsRegion }}
      authenticationRef:
        name: {{ include "app.fullname" $ }}-auth
    {{- end }}
{{- end }}
