{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.app.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/{{ .Values.serviceAccount.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
{{- end }}
