app:
  env: "dev"

image:
  tag: "dev-latest"

container:
  env:
    - name: AWS_REGION
      value: ap-northeast-2
    - name: SQS_S3_EVENTS_URL
      value: "https://sqs.ap-northeast-2.amazonaws.com/ACCOUNT/team-vault-s3-events-dev"
    - name: SQS_WORK_QUEUE_URL
      value: "https://sqs.ap-northeast-2.amazonaws.com/ACCOUNT/team-vault-work-queue-dev"
    - name: S3_BUCKET
      value: team-vault-dev
    - name: DEBOUNCE_SECONDS
      value: "60"
    - name: LOG_LEVEL
      value: DEBUG
    - name: METRICS_PORT
      value: "9090"
